# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll Sandbox
email: isabela.s@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sandbox for trying jekyll features.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: isabelanastasa
github_username:  isabelanastasa

# Build settings
markdown: kramdown
